// Data fetching
export const DATA_FETCH_START = 'DATA_FETCH_START';
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS';
export const DATA_FETCH_ERROR = 'DATA_FETCH_ERROR';

// Items Filtering
export const FILTER_ITEMS_BY_NATIONALITY = 'FILTER_ITEMS_BY_NATIONALITY';
export const FILTER_ITEMS_BY_GENDER = 'FILTER_ITEMS_BY_GENDER';
export const FILTER_ITEMS_BY_NAME = 'FILTER_ITEMS_BY_NAME';
